# Generated by Django 3.0.5 on 2020-05-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200502_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='current_question',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
