# Generated by Django 3.0.5 on 2020-05-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200504_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
