# Generated by Django 3.0.5 on 2020-05-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_team_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
    ]
